name: "Deploy frontend"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  BUCKET_NAME: "diekmrcoin-privacy-tools-frontend"
  AWS_REGION: "eu-west-3"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: export short commit id
        id: short_commit_id
        run: |
          echo "SHORT_COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
          echo "SHORT_COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> .env.production
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --pure-lockfiles
      - name: Yarn build
        run: |
          REACT_APP_COMMIT_ID=${{ env.SHORT_COMMIT_ID }}
          REACT_APP_ENV=prod
          yarn build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          role-session-name: diekmrcoin-privacy-tools-deploy
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy build folder to s3
        run: |
          aws s3 sync build s3://${{ env.BUCKET_NAME }}/
      - name: Remove old files
        run: |
          aws s3 sync build s3://${{ env.BUCKET_NAME }}/ --delete
      - name: Summary
        id: Summary
        shell: bash
        run: |
          echo "Version built" >> $GITHUB_STEP_SUMMARY
          echo ${{ env.SHORT_COMMIT_ID }} >> $GITHUB_STEP_SUMMARY
          echo .env.production >> $GITHUB_STEP_SUMMARY
